stages:
 - test
variables:
 DOCKER_HOST: tcp://docker:2375/
 DOCKER_DRIVER: overlay2
 DOCKER_TLS_CERTDIR: ""
molecule:
  stage: test
  image: python:3.9
  services:
    - docker:dind
  before_script:
    - python3 -m pip install ansible molecule-docker ansible-lint yamllint
  script:
    - molecule test
  tags:
    - docker
