stages:
 - test
variables:
 DOCKER_HOST: tcp://docker:2375
 DOCKER_DRIVER: overlay2
 DOCKER_TLS_CERTDIR: ""
molecule:
  stage: test
  image: docker:18.09-dind  #molecule-ci:latest-debian
  services:
    - docker:dind
  before_script:
    - apk add --no-cache
      python3 python3-dev py3-pip gcc git curl build-base
      autoconf automake py3-cryptography linux-headers
      musl-dev libffi-dev openssl-dev openssh
    - python3 -m pip install ansible molecule-docker ansible-lint yamllint
  script:
    - molecule test
  tags:
    - docker
