---
- name: "Configure PostgreSQL. Set listen_addresses"
  ansible.builtin.lineinfile:
    dest: "{{ postgresql_config_path }}/postgresql.conf"
    line: "listen_addresses = '*'"
    regexp: "^#listen_addresses ="
    state: present
  become: true
  notify:
    - "Restart_postgresql"

- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    contype: host
    create: true
    databases: all
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    method: trust
    source: "{{ postgresql_ip }}"
    users: all
  become: true
  notify:
    - "Restart_postgresql"
