---
-
  ansible.builtin.apt:
    cache_valid_time: 86400
    name: "{{ postgresql_packages }}"
    state: present
    update_cache: true
  become: true
  name: "Install Postgresql on deb-based"
-
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: true
  become: true
  name: Start_postgresql
-
  ansible.builtin.include_tasks: configure.yml
  name: "include configure tasks"
-
  become: true
  become_user: postgres
  name: "Create app database"
  postgresql_db:
    name: "{{ postgresql_db_name }}"
    state: present
-
  become: true
  become_user: postgres
  name: "Create db user"
  postgresql_user:
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_password }}"
    state: present
-
  become: true
  become_user: postgres
  name: "Grant db user access to app db"
  postgresql_privs:
    database: "{{ postgresql_db_name }}"
    grant_option: false
    privs: all
    roles: "{{ postgresql_db_user }}"
    type: database
