---
- name: Essential Software | Update repositories cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400
-
  ansible.builtin.apt:
    name: "{{ postgresql_packages }}"
    state: present
  become: true
  name: "Install Postgresql on deb-based"

- name: Stop postgresql
  ansible.builtin.service:
    name: postgresql
    state: stopped
  become: true

- name: Synchronization of two paths both on the control machine
  ansible.posix.synchronize:
    src: "{{ postgresql_path_data_direcroty }}"
    dest: "{{ postgresql_destination_data }}"
  delegate_to: "{{ inventory_hostname }}"

- name: "Configure PostgreSQL. Set listen_addresses"
  ansible.builtin.lineinfile:
    dest: "{{ postgresql_config_path }}/postgresql.conf"
    regexp: "^#listen_addresses ="
    line: "listen_addresses = '*'"
    state: present
  become: true

- name: "Configure PostgreSQL. Change default data_directory"
  ansible.builtin.lineinfile:
    dest: "{{ postgresql_config_path }}/postgresql.conf"
    regexp: "^data_directory = "
    line: data_directory = '{{ postgresql_new_path_data_directory }}'
    state: present
  become: true

- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    contype: host
    create: true
    databases: all
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    method: trust
    source: "{{ postgresql_ip }}"
    users: all
  become: true

- name: Start postgresql
  ansible.builtin.service:
    name: postgresql
    state: started
  become: true
-
  become: true
  become_user: postgres
  name: "Create app database"
  postgresql_db:
    name: "{{ postgresql_db_name }}"
    state: present
-
  become: true
  become_user: postgres
  name: "Create db user"
  postgresql_user:
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_password }}"
    state: present
-
  become: true
  become_user: postgres
  name: "Grant db user access to app db"
  postgresql_privs:
    database: "{{ postgresql_db_name }}"
    grant_option: false
    privs: all
    roles: "{{ postgresql_db_user }}"
    type: database
