---
-
  ansible.builtin.lineinfile:
    dest: "{{ postgresql_config_path }}/postgresql.conf"
    line: "listen_addresses = '*'"
    regexp: "^#listen_addresses ="
    state: present
    mode: 0644
  become: true
  name: "Configure PostgreSQL. Set listen_addresses"
  notify: Restart_postgresql
-
  become: true
  name: "Allow md5 connection for the db user"
  notify: Restart_postgresql
  postgresql_pg_hba:
    contype: host
    create: true
    databases: all
    dest: "{{ postgresql_path_to_hba }}"
    method: trust
    source: "{{ postgresql_ip }}"
    users: all
