---
 - name: Update all packages to their latest version
   apt:
      update_cache: true
      name: "*"
      state: latest
   become: true

 - name: Install Postgresql on deb-based
   apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-pip
      - libpq-dev
      - python-dev
      - python-setuptools
    state: present
    update_cache: true
    cache_valid_time: 86400
   become: true
   notify: postgres_restart

 - name: Install Python module for vagrant
   pip:
    name:
     - psycopg2
     - psycopg2-binary
    state: present
   become: true

 - name: Create app database
   postgresql_db:
    state: present
    name: "{{ db_name }}"
   become: true
   become_user: postgres

 - name: "Create db user"
   postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
   become: true
   become_user: postgres

 - name: "Grant db user access to app db"
   postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: all
   become: true
   become_user: postgres

 - name: "Allow md5 connection for the db user"
   postgresql_pg_hba:
    dest: "/etc/postgresql/12/main/pg_hba.conf"
    contype: host
    databases: all
    source: 192.168.56.1
    method: md5
    users: "{{ db_user }}"
    create: yes
   become: true
   become_user: postgres
   notify: postgres_restart
