---
-
  ansible.builtin.apt:
    cache_valid_time: 86400
    name:
      - postgresql
      - postgresql-contrib
      - python3-pip
      - libpq-dev
      - python-dev
      - python-setuptools
      - virtualenv
      - python3-psycopg2
    state: present
    update_cache: true
  become: true
  name: "Install Postgresql on deb-based"
  notify: Restart_postgres
-
  become: true
  become_user: postgres
  name: "Create app database"
  postgresql_db:
    name: "{{ postgresql_db_name }}"
    state: present
-
  become: true
  become_user: postgres
  name: "Create db user"
  postgresql_user:
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_password }}"
    state: present
-
  become: true
  become_user: postgres
  name: "Grant db user access to app db"
  postgresql_privs:
    database: "{{ postgresql_db_name }}"
    grant_option: false
    privs: all
    roles: "{{ postgresql_db_user }}"
    type: database
-
  become: true
  become_user: postgres
  name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    contype: host
    create: true
    databases: all
    dest: "{{ postgresql_path_to_hba }}"
    method: md5
    source: "{{ postgresql_ip }}"
    users: "{{ postgresql_db_user }}"

-
  name: "Stop service postgresql for change data directory of postgresql"
  ansible.builtin.service:
    name: postgresql
    state: stopped
  become: true

-
  name: Synchronization using rsync protocol (push)
  ansible.posix.synchronize:
    src: "{{ postgresql_sourcepath_to_data }}"
    dest: rsync://"{{ postgresql_destpath_to_data }}"

- name: "Change postgresql data"
  ansible.builtin.lineinfile:
    path: "{{ postgresql_path_to_config }}"
    regexp: '^data_directory='
    line: data_directory = '/mnt/volume-nyc1-01/postgresql/12/main'
  become: true

-
  name: "Start service postgresql"
  ansible.builtin.service:
    name: postgresql
    state: started
  become: true
