--- 
- 
  ansible.builtin.apt: 
    cache_valid_time: 86400
    name: 
      - postgresql
      - postgresql-contrib
      - python3-pip
      - libpq-dev
      - python-dev
      - python-setuptools
    state: present
    update_cache: true
  become: true
  name: "Install Postgresql on deb-based"
  notify: Postgres_restart
- 
  ansible.builtin.pip: 
    name: 
      - psycopg2
      - psycopg2-binary
    state: present
  become: true
  name: "Install Python module for running  into vagrant"
- 
  become: true
  become_user: postgres
  name: "Create app database"
  postgresql_db: 
    name: "{{ db_name }}"
    state: present
- 
  become: true
  become_user: postgres
  name: "Create db user"
  postgresql_user: 
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present
- 
  become: true
  become_user: postgres
  name: "Grant db user access to app db"
  postgresql_privs: 
    database: "{{ db_name }}"
    grant_option: false
    privs: all
    roles: "{{ db_user }}"
    type: database
- 
  become: true
  become_user: postgres
  name: "Allow md5 connection for the db user"
  notify: postgres_restart
  postgresql_pg_hba: 
    contype: host
    create: true
    databases: all
    dest: "{{ path_to_hba }}"
    method: md5
    source: "{{ ip }}"
    users: "{{ db_user }}"
