---
-
  ansible.builtin.apt:
    cache_valid_time: 86400
    name:
      - postgresql
      - postgresql-contrib
      - python3-pip
      - libpq-dev
      - python-dev
      - python-setuptools
      - virtualenv
      - python3-psycopg2
    state: present
    update_cache: true
  become: true
  name: "Install Postgresql on deb-based"
-
  become: true
  become_user: postgres
  name: "Allow md5 connection for the db user"
  notify: Restart_postgres
  postgresql_pg_hba:
    contype: host
    create: true
    databases: all
    dest: "{{ postgresql_path_to_hba }}"
    method: trust
    source: "{{ postgresql_ip }}"
    users: all
-
  name: "Configure PostgreSQL. Set listen_addresses"
  lineinfile:
    dest: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp: "listen_addresses ="
    line: "listen_addresses = '*'"
    state: present
  become: true
  become_user: postgres
-
  become: true
  become_user: postgres
  name: "Create app database"
  postgresql_db:
    name: "{{ postgresql_db_name }}"
    state: present
-
  become: true
  become_user: postgres
  name: "Create db user"
  postgresql_user:
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_password }}"
    state: present
-
  become: true
  become_user: postgres
  name: "Grant db user access to app db"
  postgresql_privs:
    database: "{{ postgresql_db_name }}"
    grant_option: false
    privs: all
    roles: "{{ postgresql_db_user }}"
    type: database
