---
driver:
  name: docker
lint: |-
    yamllint .
    ansible-lint .
platforms:
  -
    hostname: ubuntu
    image: "mpaivabarbosa/molecule-systemd-ubuntu:20.04"
    name: db
    override_command: false
    pre_build_image: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
verifier:
  name: ansible
